### ISSUE TITLE
Grant access to OHSU S3 bucket to HMS IAM role user

### ISSUE THREAD

**Issue by jmuhlich** [ncihtan/IDP#1]
The ARN of our role user is as follows:
`arn:aws:iam::292075781285:user/idp-import`

**Comment by xdoan** [comment]
@jmuhlich  you should have access to s3://htan-dcc-ohsu now!

**Comment by jmuhlich** [comment]
I don't seem to have the ListObjects permission, unless there are some extra constraints I'm not aware of.

**Comment by jmuhlich** [comment]
I can list and get objects, but not put. If that's the expected permissions then we're all set.

**Comment by xdoan** [comment]
I think that's expected, do you require put permissions?

**Comment by xdoan** [comment]
@jmuhlich just remembered that you're probably getting access denied because we require an extra flag when people put objects into buckets so we have full control over them: https://ncihtan.github.io/HTAN-Data-Ingress-Docs/programmatic-upload-aws-cli.html

**Comment by jmuhlich** [comment]
I didn't need put permissions, just testing the boundaries. Good to know about the docs for upload though. I think this is resolved.
