### ISSUE TITLE
Check we can publish a minerva story

### ISSUE THREAD

**Issue by ychae** [ncihtan/IDP#14]
From the 2/5 IDP meeting:

Ensure that we can publish a minerva story (e.g. generating jpeg files, and other Minerva inputs artifacts for each source image and associated Minerva story) via deploying a headless Minerva publishing tool to be provided by Jeremy's team

**Comment by milen-sage** [comment]
see #18

**Comment by milen-sage** [comment]
@elysekozlowski and @ychae looks like there are some issues in IDP that are overlapping could we consolidate?

**Comment by elysekozlowski** [comment]
consolidating with #18
