### ISSUE TITLE
Production EC2 instance for DSA

### ISSUE THREAD

**Issue by ychae** [ncihtan/IDP#23]
### Prod server requirements:

- Should be the same as the dev server; provision the same resource
- This is going to be ~~the~~ a public facing image viewer portal available for HTAN -- gateway to access image resources
- Bruno will work with the IT team to get this set up, if there are any additional requirements that come up, send it in the #htan slack channel
- will contain the stable, tested code and QC-ed/de-id-ed data

**Timeline**: May 17, 2021

**Comment by milen-sage** [comment]
@ychae just to clarify and reflect take aways from our earlier discussion:
- DSA is **a** public facing image viewer portal for HTAN, not **the** one gateway to access the images
- we will ramp up work on improving Minerva story workflows (e.g. integration with metadata curation during imaging ingress, integration with downstream services (i.e. data portal), robust update process of headless Minerva publishing service to enable support for upcoming Minerva features around image exploration), as well as OMERO integration with data ingress services.

**Comment by ychae** [comment]
@smrgit update re: status of this instance:

The AWS account has been deployed. Bruno will move his PR from sandbox to `htan-dev` and Sage-IT will hopefully merge it today.

**Comment by BrunoGrandePhD** [comment]
I'm waiting for reviews from Sage IT [here](https://github.com/ncihtan/aws-htan-infra/pull/1) and [here](https://github.com/ncihtan/aws-htan-infra/pull/2).

**Comment by BrunoGrandePhD** [comment]
**Progress Update**

The first PR has been merged. The second PR is still being discussed with Sage IT, who have raised some security concerns. I'm in the process of figuring out the best way forward. Stay tuned. 

/cc @smrgit

**Comment by BrunoGrandePhD** [comment]
The EC2 instance (`i-0af95d82a0f109979`) has been deployed [here](https://github.com/Sage-Bionetworks/aws-htan-infra/blob/main/config/dev/dsa-prototype-ec2.yaml) with a private IP of `10.255.31.41`. I confirmed that I could access a port on the instance using this command (after installing the AWS CLI and session manager plugin):

```
# If on macOS:
#   brew install awscli
#   brew install --cask session-manager-plugin

aws ssm start-session --target "i-0af95d82a0f109979" --document-name "AWS-StartPortForwardingSession" --parameters '{"portNumber":["80"],"localPortNumber":["8080"]}'
```

If you need access let me know and we can set that up.
