### ISSUE TITLE
Curate list of all Synapse group IDs that should have access to OMERO

### ISSUE THREAD

**Issue by jmuhlich** [ncihtan/IDP#5]
Where would this list be maintained? I saw #4 was created and closed but it doesn't mention where to find the list of IDs. Is the SOP to just update the live OMERO OAuth configuration whenever a new group is created?

**Comment by xdoan** [comment]
Do you have access to the HTAN IDP slack? I posted the list there and @ you with a note that last week I wasn't able to create a github issue (I since have more permissions)
